### ISSUE TITLE
AttributeError: 'Waypoint' object has no attribute 'lat'.

### ISSUE THREAD

**Issue by larsks** [sgraaf/gpx#19]
This looks like a typo:

```
>>> wpt = gpx.Waypoint()
>>> wpt.latitude = 52.123
>>> wpt.longitude = 4.123
>>> g.waypoints.append(wpt)
>>> print(g.to_string())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.12/site-packages/gpx/gpx.py", line 300, in to_string
    gpx = self._build()
          ^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/gpx/gpx.py", line 234, in _build
    gpx.append(_waypoint._build())
               ^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/gpx/waypoint.py", line 179, in _build
    waypoint.set("lat", str(self.lat))
                            ^^^^^^^^
AttributeError: 'Waypoint' object has no attribute 'lat'. Did you mean: 'sat'?
```

**Comment by sgraaf** [comment]
Hi, thank you for using `gpx` and reaching out! 😃

This it not a typo, at least not on our end. The actual property names for latitude and longitude are `lat` and `lon`, respectively. For reference, check out the [API reference on the Waypoint object](https://gpx.readthedocs.io/en/stable/api.html#module-gpx.waypoint).

The code snippet below works as advertised:

```python
>>> from gpx import GPX, Waypoint
>>> g = GPX()
>>> wpt = Waypoint()
>>> wpt.lat = 52.123
>>> wpt.lon = 4.123
>>> g.waypoints.append(wpt)
>>> print(g.to_string())
<gpx version="1.1" creator="PyGPX">
  <wpt lat="52.123" lon="4.123"/>
</gpx>
```

**Comment by larsks** [comment]
I think there's clearly a bug. That example was copy-and-pasted straight from [the README](https://github.com/sgraaf/gpx?tab=readme-ov-file#manipulating-gpx-data).

**Comment by larsks** [comment]
I'm happy to open a new document bug if you would prefer.
